### PR TITLE
added spambot module

### PR DESCRIPTION
**Pull request by ForestMars**
Adding spambot as per #281

### CODE REVIEW

**Comment by esod** [comment]
I'll pull the module to live and enable it.

**Comment by esod** [comment]
200 user accounts per cron doesn't seem to stress the test environment. We have 1696 accounts so it will still take a few hours to go through.

I'm blocking the user account for Action to take when the account is a match for spam.

**Comment by ForestMars** [comment]
Ok so when we are pulling our reg list, we need to pull only active users.

**Comment by esod** [comment]
At this moment, Spambot still has 818 accounts to check and spambot isn't getting us anywhere. The last checked user account is http://www.nyccamp.org/user/mndkajskdasjkdj (see screenshot) and mndkajskdasjkdj is not blocked. 

spambot-isnt-getting-us-anywhere

**Comment by ForestMars** [comment]
Yes I know, I just checked. We didn't start to get spam until this year, so most of the 900 accounts it already checked in the last 4+ hours are all legit. 

In fact, I'm seeing a LOT of legit accounts. I think we're going to be completely maxed out on space if people actually show up.

**Comment by esod** [comment]
I suppose there are worse problems than being completely maxed out on space although it does make logistics that much more important and crucial.

What do we do about Mr. mndkajskdasjkdj's and similar accounts. Cherry pick them out?

**Comment by ForestMars** [comment]
The Mr. mndkajskdasjkdj's of the world will need to be cherry-picked for deletion. I've had good luck with spambot module (deleting thousands of phony users automatically) although my understanding is that it goes by IP, not regex'ing their name. 

I've also gone ahead and added a required field for new users to say where they heard of NYC Camp, which should enable us to easily prune the bots. 

Edit: I actually don't know a module to prune with a regex expression. So when I've done that in the past I've had to do that directly with a database query.

**Comment by ForestMars** [comment]
Worth noting that Spambot left mr. mndkajskdasjkdj set to active, (and his email is "ljdlasjldsjljasd@jdakdjslkac.ca") so I'm not very hopeful here.

**Comment by esod** [comment]
Maybe spambot will do better with new accounts. 

Cherry picking the spam accounts is not going to be simple either.  It might be easier to spot the spammed email addresses than the spammed usernames? http://www.nyccamp.org/user/nabilmidani is not not spam.

**Comment by ForestMars** [comment]
TBH I think we might have better luck with a custom/creative solution than something like spambot, which works better when you have a much higher spam volume. 

I'm thinking something along the lines of required profile picture, "how do you find out about NYC Camp" field, and maybe add in Spamicide too?

**Pull request merged**
