### PR TITLE
Issue #68 - adding schedule icon and move camp program to the mobile slide nav

### PR DESCRIPTION
**Pull request by sergesemashko**

### CODE REVIEW

**Comment by sergesemashko** [comment]
ok, I'll translate everything to the px, and move to separated js file to avoid bad patterns.

**Comment by sergesemashko** [comment]
Oops, @mirie accidentally pushed changes into wrong repo and this request looks like it merged, but please review the changes once again.

**Comment by mirie** [comment]
Hey @Sergey-Semashko, this looks fine -- are you opening a new pr to master?

**Comment by sergesemashko** [comment]
@mirie yes, please take a look at #127

**Pull request merged**
