### PR TITLE
nyccamp.module addition with node/add workaround

### PR DESCRIPTION
**Pull request by likewhoa**
This is a workaround for issue #36. Currently what we have is not ideal for the time being as what you get is 
untitled

And normally you would click on "Add new content" but this links to "/node" which is the same place the path alias for "node/add" points to thus creating a loop. 

I know @willy said that Earl Miles uses panels to protect node/add access but until then this simply piece of code can allow site administrators to access "node/add" without being redirected to "/node".

### CODE REVIEW

**Comment by jonpugh** [comment]
Instead...
Change the name of this module to nyccamp_hacks.module so we know what it is.

Use a hook.  You don't want to add code outside a hook because it would run on every page unnecessarily.

``` php
<?php
/**
 * Implements hook_menu_alter()
.*/
function nyccamp_hacks_menu_alter(&$items){
   $items['node/add']['access callback'] = 'nyccamp_hacks_node_add_access';
}

/**
 * Custom access callback for node/add
 * Only allow users with "administer nodes" permission to view node/add page.
.*/
function nyccamp_hacks_node_add_access(){
  return user_access('administer nodes');
}
```

**Comment by esod** [comment]
The module doesn't do the redirect. It just checks access. The user is still on the page, which is not what we want. 

How about this contrib module:

https://drupal.org/project/pathrules

and this rule:

<code>
{ "rules_redirect_certain_users_away_from_node_add" : {
    "LABEL" : "Redirect certain users away from node\/add",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "TAGS" : [ "nyccamp", "nyccamp-hacks" ],
    "REQUIRES" : [ "pathrules", "rules" ],
    "ON" : { "init" : [] },
    "IF" : [
      { "pathrules_checkpath" : { "path" : "node\/add", "operation" : "equals" } },
      { "NOT user_has_role" : {
          "account" : [ "site:current-user" ],
          "roles" : { "value" : { "3" : "3" } }
        }
      }
    ],
    "DO" : [ { "redirect" : { "url" : "\u003Cfront\u003E" } } ]
  }
}
</code>

**Comment by esod** [comment]
This looks good on the schedules branch. go here 

http://schedules-nyccamp2014.gotpantheon.com/node/add

Different user experience for admin, auth and anon

**Comment by likewhoa** [comment]
@esod what are you referring to? I assume @jonpugh code since I didn't test it because I did test mine and it works as advertise. Anyways, your rule will always be evaluated which is what @jonpugh wanted to avoid with the hook_menu_alter but even that get called on every page.

I vote for @jonpugh since it's more drupal centric and easy to understand. The rule is just overkill for this purpose.

**Comment by esod** [comment]
I don't think I was clear. The user is still on the page with @jonpugh's code. There is no redirect which I think is good UX.

I was concerned about your code because of syntax; the space between the exclamation point and in_array() and the use of in_array() when I'm guessing Drupal has a method for that already baked-in. Also drupal_goto() is the same as drupal_goto('front'). (Greater than and less than signs removed because Github's filter is removing them).

If rules are not performant, let's not go that route. I think the rule is a good idea because since we seem well on our way to refactoring COD, rules are an easy entry point for others at other events who may prefer our distribution.

**Comment by likewhoa** [comment]
I'll test @jonpugh code locally to see what you mean. w.r.t to the rule being good for users that will use the distro, I don't really agree since what we are doing is and should be a temporally workaround a problem which we should address, hence why this should be consider a hack not a solution.

I would have made the rule but figure why since it will eventually be removed once the real problem is resolved. w.r.t to github removing stuff.. you should just escape the "<...>". ;)

**Comment by likewhoa** [comment]
@esod his code works as advertise, you probably need to clear your cache or you didn't notice it's for nyccamp_hacks.module not nyccamp.module like in my pr. I am closing this issue since I prefer his method.

**Comment by jonpugh** [comment]
User experience is not an issue here. We don't link to node/add anywhere,
so only curious users will look for the page.

There is really no difference to end users that matter. This is a temporary
fix to a bad bug.

@forestmars hook_menu_alter is only called when menu cache clears.

**Pull request closed without merging**
