### PR TITLE
This fixes an issue I encountered when I tried to create a new content t...

### PR DESCRIPTION
**Pull request by likewhoa**
...ype called 'sponsorship' and to my surprise it was

not showing up in the UI, so after banging my head a couples of times on the keyboard I entered mysql console and noticed that
the node_type table actually had my newly created content type but the problem was that the 'sponsorship option' content type
had the same orig_type value as my newly created content type so drupal got confused. Anyways, this patch will prevent anyone
from entering a duplicate machine readable name on content types in which their orig_type is the same.

see https://drupal.org/node/515454 for info on this core bug

### CODE REVIEW

**Comment by mirie** [comment]
@ForestMars, can you comment on this one?

**Comment by ElijahLynn** [comment]
Do we have a way of tracking patches we have applied? This will get overwritten on next update.

**Comment by ElijahLynn** [comment]
Also, I don't think should merge our own pull requests.

**Comment by likewhoa** [comment]
Only new modules that get added will eventually need the correct permissions applied. How do you think it will get overwritten on the next update? 

w.r.t to the merge, I had the go ahead from @mirie on applying it, I guess i should have waited for :+1:  first or :icecream: :D

**Comment by likewhoa** [comment]
oh wait @ElijahLynn i was thinking of another pr I made, not this one. You're right a core update will overwrite this one and this I didn't anticipate.

**Comment by ElijahLynn** [comment]
We just discussed IRL at the Playday and we are going to make a PATCHES.txt file in root. I will submit this as a PR and link to this discussion.

**Comment by mirie** [comment]
hey @likewhoa, I think we had a miscommunication here -- I don't think I approved this one offline. I would have approved it on this PR in a comment (like the other PR). It's ok though.

**Comment by likewhoa** [comment]
gotcha @mirie

**Pull request merged**
