### PR TITLE
configures sessions layout through display suite layouts and fields

### PR DESCRIPTION
**Pull request by esod**
This pull request corrects a layout issue with the sessions where the Add to your sessions flag is printing on Pending, Unprocessed, and Declined session nodes. Display suite is preventing the three lines of code I wrote in node.tpl.php from implementing this user experience. I'm creating a feature to, at the least, not have all this required configuration exist only in the database. 

That being said, please check the following pages for the difference. 

Example for a Pending session:
http://www.nyccamp.org/session/drupal-business-professionals
vs
http://qr-code3-nyccamp2014.gotpantheon.com/session/drupal-business-professionals

Example for  an Unprocessed session:
http://www.nyccamp.org/session/power-dark-side-what-drupalers-can-learn-wordpress
vs
http://qr-code3-nyccamp2014.gotpantheon.com/session/power-dark-side-what-drupalers-can-learn-wordpress

Example for a Declined session example:
http://www.nyccamp.org/session/integrating-google-analytics-your-drupal-7-site
vs
http://qr-code3-nyccamp2014.gotpantheon.com/session/integrating-google-analytics-your-drupal-7-site
http://www.nyccamp.org/session/power-dark-side-what-drupalers-can-learn-wordpress
http://qr-code3-nyccamp2014.gotpantheon.com/session/power-dark-side-what-drupalers-can-learn-wordpress

### CODE REVIEW

**Comment by ForestMars** [comment]
You are really getting into it with display suite!

**Comment by esod** [comment]
I guess so. It's a lot of overhead for something I can more easily do in code.

**Comment by likewhoa** [comment]
@esod and why can't you do this through code? I really dislike DS.

**Comment by esod** [comment]
@likewhoa the problem is Display Suite, not the code. That's what I've been saying.

**Comment by esod** [comment]
Display suite requires me to do these changes in order to resolve the bug. It's not a question of whether I like Display suite or not. I said in the pull request that "Display suite is preventing the three lines of code I wrote in node.tpl.php from implementing this user experience".

I did want to create a pull request for this so we could open a discussion about Display Suite. But I need to get these configuration changes out to resolve the bug.

**Pull request merged**
