### PR TITLE
Regapp integration

### PR DESCRIPTION
**Pull request by Offlein**
Hi, I should've PR'd this a while ago. Minor change that has a big impact.

### CODE REVIEW

**Comment by Offlein** [comment]
So, what, bugfixes don't improve things?!

**Comment by ForestMars** [comment]
Ones that cause regressions would be an obvious example.

**Comment by Offlein** [comment]
Point taken.

**Comment by Offlein** [comment]
Actually, no, I take that back. This was specified as an "improvement" and hence comes with the Craig Leinoff Guarantee of no regressions! I win!

**Pull request merged**
