### PR TITLE
153 - makes directions page map responsive

### PR DESCRIPTION
**Pull request by rabellamy**

### CODE REVIEW

**Comment by ForestMars** [comment]
It looks like you can't scroll past the Google map, at least on my HTC One Android (Jelly Bean.) 

The map loads, but there's no way to scroll past it to the rest of the page.

**Comment by rabellamy** [comment]
@ForestMars which environment?

**Comment by ForestMars** [comment]
Looks like it's working on Dev but not on Test.

**Comment by rabellamy** [comment]
@ForestMars try here:
http://google-map-nyccamp2014.gotpantheon.com/directions

**Comment by ForestMars** [comment]
"nice."

**Pull request merged**
