### PR TITLE
Event registration feature, enabling rule for email sending

### PR DESCRIPTION
**Pull request by sergesemashko**
@TODO group events by type, I'm getting an error during form building, probably memory limit is exceeded. Going to investigate it later.

### CODE REVIEW

**Comment by ForestMars** [comment]
Why is the master branch just now merging in cod/profiles/contrib/ctools?

**Comment by mirie** [comment]
Is this the same code that @rabellamy asked me to test out on Integration the other day? This doesn't seem (at first glance) to address the comments I added to the trello card: https://trello.com/c/8oEImKfq/3-event-registration-feature

**Comment by sergesemashko** [comment]
This is the same code, except of event_registration.install file. I'll ask Tony today what brach he used and recreate pull request. Sounds good?

**Comment by ForestMars** [comment]
Did this get updated?

**Pull request closed without merging**
