### PR TITLE
Migrate users

### PR DESCRIPTION
**Pull request by mirie**

### CODE REVIEW

**Comment by mirie** [comment]
This is missing the field organization adjustments because I am unsure of how this info will be stored.

This uses the install hook to adjust the fields on the user profile.

I'm not sure what to do with the features -- if I need to do anything at all. Advice is most appreciated!

Also, I'm not sure why Eric's commits are in this PR. I followed Eric's instructions. Please let me know in the comments how to avoid this in the future. Thanks!

**Comment by Offlein** [comment]
I read all the code here. It seemed legit to me -- I only just got a chance to look at it though so I haven't run it. I'm about to go home ..I'll start the call on my phone en route, and then when I get there, I'll actually apply this on my own install and confirm it works.

**Comment by Offlein** [comment]
Call to undefined function drush_log() in /var/www/sites/all/modules/CUSTOM/nyccamp_migrate/nyccamp_migrate.install on line 85

So, this module will actually crash and fail if enabled through the GUI.. we should fix that some how. Or somehow prohibit it from being installed through the GUI. Or deal with it.

It looks like it's run OK otherwise?

**Comment by mirie** [comment]
Ah yes, that's true. I forgot about that -- what's a better way to output messages that doesn't crash the gui?

**Comment by Offlein** [comment]
I'm actually not sure; typically watchdog() will log well, but I don't know if that will print in the way you want with Drush. I think it might? Maybe someone else can weigh in? (..Yeah right.)

**Comment by mirie** [comment]
Ok, I've thought it over -- since it's in hook_install(), I think your idea of changing the messages to watchdog() is best.

**Comment by ForestMars** [comment]
That definitely sounds good. I wanted to take a closer look at the code, but the fork and pull workflow setup is killing me. Would love if we could switch over to team model and keep all our topic branches in the same repository.

**Comment by mirie** [comment]
Forest, can you reach out to Tony to discuss the workflow? He's leading that and helps to onboard people.

**Comment by ForestMars** [comment]
I'm all about reaching out.

**Comment by mirie** [comment]
Cool! He's ready and waiting to discuss in #nyccamp :) Thanks. I'll commit an update for those watchdog changes later today.

**Comment by ForestMars** [comment]
I'm underground on the train right now and then I have meetings but we'll
catch up later this afternoon

Mai can you please forward this email to Tony so he's in the loop

**Comment by mirie** [comment]
@Offlein: Updated for: watchdog and drush_log()

**Comment by jonpugh** [comment]
watchdog is all you need.  If you want to see watchdog calls while using drush, just use the `-v` option:

```
 jon@edison ~ $ drush @eny eval 'watchdog("debug", "hiya");' -v
 Loaded alias @eny from file /home/jon/.drush/drush.aliases.drushrc.php                                       [notice]
Initialized Drupal 7.26 root directory at /home/jon/Repos/pcg/engageny2/docroot                              [notice]
Initialized Drupal site eny at sites/eny                                                                     [notice]
Loading outputformat engine.                                                                                 [notice]
WD debug: hiya                                                                                               [notice]
Command dispatch complete                                                                                    [notice]
```

**Comment by jonpugh** [comment]
The reason @esod's commits are showing is that they don't exist in the `NYC-Camp:integration` branch.

He should merge his changes into that repo/branch.

**Comment by jonpugh** [comment]
His commits do exist in `master`, so  `integration` is behind `master`.  If you `git checkout integration` then `git merge master` then `git push origin master` it should remove those commits from this pull request.

**Comment by mirie** [comment]
Ok! Made some edits -- see commit comment :)

**Comment by mirie** [comment]
I kept the variable in function _migrate_to_terms() line 106. That's the only function I use $can_drush_log in.

**Comment by mirie** [comment]
ok, ok. I'll remove the drush_log() calls. I think I'll get rid of all of them anyways as I used them for debugging. Thanks for the advice!

**Comment by jonpugh** [comment]
:icecream:

**Pull request merged**
