### PR TITLE
Theming of EVA for Event Schedules

### PR DESCRIPTION
**Pull request by willykaram**
This a PR for theming related the schedules for Events. Obviously this could be better, however, hopefully this will do for now.
- http://wk-theming-nyccamp2014.gotpantheon.com/2014/summit/apps-startup
- http://wk-theming-nyccamp2014.gotpantheon.com/2014/summit/commerce-summit
- http://wk-theming-nyccamp2014.gotpantheon.com/2014/summits/digital-publishing-media
- http://wk-theming-nyccamp2014.gotpantheon.com/event/un-training-day

The EVA for these is here and DS settings are all configured (including removal of the <br> that was harcoded into the sessions flag field):
- http://wk-theming-nyccamp2014.gotpantheon.com/admin/structure/views/view/schedule_event_eva/edit

### CODE REVIEW

**Comment by esod** [comment]
All I see here is:

http://wk-theming-nyccamp2014.gotpantheon.com/2014/summit/apps-startup

is green. The green overwhelms. Make the flag bold and blue.

Same on all the other pages. The green overwhelms. Make the flag bold and blue. We expect our users to know that words are buttons. That's Drupal. 

I appreciate the effort here. Hey, my module is front and center. Well, it does work great, even if I do say so myself. 

In graphic design, boxes are confining and their use should be avoided or minimized.

boxes-are-confining

Photos, for instance, are boxy. For the most part that can't be helped. But the other arrows on the screen shot point to areas where we could rethink the design, although, obviously, not at this time.

We, of course, want an overall design concept that is different that what we have this year. Just putting this graphic design concept out there.

**Comment by esod** [comment]
The functionality is super. I plan to study it to understand it. I hate (hate being too a strong word) that I can't place the flag where I want on http://www.nyccamp.org/program/sessions-schedule because I don't have code and its a View in a Display suite display.

**Comment by esod** [comment]
A few more edits. Comments on the screen shot
make-the-font-size-and-pictures-larger

**Comment by esod** [comment]
Everything looks very small in the schedule. Perhaps a little more air (air is a graphic design term for space) between Ross Nunamaker's photo and Nick Vahalik's photo. 

It's is nice the way the sessions fit together as units of information. Everything just look a little tiny to me. I'm checking it on ie9 on Windows 7 where the fonts are usually larger, and it still looks too small.

**Comment by esod** [comment]
But mostly I just want to see the flags not overwhelm everything else on the page.

**Comment by willykaram** [comment]
WRT color, the UN team has requested a prominent button to make thing more
obvious, so it's less "confusing" our to register/add sessions to their
schedule. WRT to sizing, the current avatar and font sizes are roughly
consistent with those used by Facebook (i.e., 50px avatar).

I'd prefer to follow-up a middle road on the sizing to so that we can use
the same for desktop and mobile. If we go larger here for desktop, we then
need to refine for mobile breakpoints. Unless these sizing refinements are
show stoppers, I suggest the we defer on these small refinements in order
to focus on other bigger theming issues, like the partner page, third
column (which are major issues). I'm just trying to keep it simple and get
this done as a basic solution to #205.

**Comment by esod** [comment]
Let's let the sizing stuff go. Let's talk about the button. 

A good rule of thumb in graphic design or interior design or any design milieu, is to introduce a new color only when the color is introduced three times. What about a blue background for the button and white bold text? That way we're satisfying the UN team's request without breaking the design rule of thumb.

A blue button with white text will be very strong (graphic design term) on schedule pages but so be it.

**Comment by esod** [comment]
a-new-color

And, of course you will fix the height of the button. Even a black background (or maybe dark gray) for the button will work too.

**Comment by willykaram** [comment]
We have and will continue to have the green in many instances, an it's
something we've been using since 2012. For our key calls to action, we
should likely be having a different color, such as the green -- i.e, what
is the one item on the page that we want users to click focus on. This
color scheme/theming is also consistent with the designs/style tiles that
were produced and handed off to the theming team/posted to Trello (as well
as a send iteration of lighter blue/white design that Rainer prepared). Try
to stay somewhat in line with what the team agreed upon.

WRT the height of the button, as noted in the original PR, this post
contemplates removing the <br> that's currently hardcoded into the custom
DS field.

**Comment by willykaram** [comment]
I'd also suggest that there are a number of tweaks, refinements and
improvement we can make to the theming that's implemented in this PR
(ideally we can do a bit of that later this wee). It's not an ideal
implementation, but rather a first step at getting us something since right
now we have nothing and all of the schedule for event have been hard coded
into the event nodes with tables and manual links to the sessions (or in
some cases nothing). The area where this is likely most pressing at the
moment is for the UN training day, where we need to get an update back to
their team asap (see
http://wk-theming-nyccamp2014.gotpantheon.com/event/un-training-day).

**Comment by willykaram** [comment]
BTW, we also have communications going out to attendees later today by
email, and it would be helpful to have this theming/functionality (or some
variant) implemented by then as well.

**Comment by esod** [comment]
What we're talking about here is not theming. It's developing layouts and I think you're doing this layout work without the benefit of design. The green background is too strong. It doesn't belong there.

I'll remove the extra <br>. That was an earlier attempt to get this to look like something.

**Comment by esod** [comment]
$ltbr&gt

**Comment by willykaram** [comment]
Can we agree to improve on the green button and try to make it more subtle
later in the week? Given that some of the feedback we're getting from
users's is that they're confused/lost, we're likely better to overwhelm
them than underwhelm them. Forest seemed to be find with the green button
as he merged the other PR with this in place yesterday, so I think we
should also get some input from others on the team as we refine over the
week -- particularly Rainer, who's been handling much of the design work.

**Comment by esod** [comment]
My last comment seems to not be printing.

Sure. I'll merge it and you can pull it to live and do whatever checklist items are necessary.

**Pull request merged**
