### PR TITLE
Adds the QR code

### PR DESCRIPTION
**Pull request by esod**
This is a better pull request. It's cleaner and up-to-date with the current master. I'll close #150.

After we deploy this code, Each user will have a QR code tab on their user profile with their first name last name and organization currently set for default text. We can change the contents of QR code at any time by changing the contents of the mobile field in the users fields and in the rule, both of which fields accept tokens.

### CODE REVIEW

**Comment by esod** [comment]
You can see this code in actions here:

http://qr-code3-nyccamp2014.gotpantheon.com/user/YOURID/qr-code

**Comment by likewhoa** [comment]
@esod Did you add the field permissions access for users who wish to allow their qrcode to be viewed by others? Also, I see you didn't add a template for the 'page not found' on qrcodes that are not made public.

**Comment by esod** [comment]
We're thinking of using the QR code to expedite registration at the UN. User access is another usage.

I'm not creating a custom 404 page until I receive creative direction and a layout from the graphic designer. I apologize if I didn't make that clear previously.

Will you please merge this in? I think Willy and Mai can start to think of ways to use the QR code once they have in front of them. Any other changes we'd like to make are configuration changes and don't necessarily require code. Thanks

**Comment by likewhoa** [comment]
Thanks for clarifying. :+1:

**Comment by esod** [comment]
Thank you. Another notch on my belt, dontchaknow

**Pull request merged**
