### PR TITLE
Adding Organizations, tweaking Sponsor

### PR DESCRIPTION
**Pull request by Offlein**
Hi,

This adds an Organization group. Organizations take two fields (Drupal Association and Our Modules) that were previously in Sponsor. They are subsequently removed from the cod_sponsor Feature (but I think Features won't do that automatically; you have to do it manually). Also adds a "group_org_user" field to user entities so that Organization memberships are separate from other memberships.

I didn't affect the display of Sponsors OR Organizations. But I could if need be. I have a little more time this week than last.

### CODE REVIEW

**Comment by Offlein** [comment]
Er.. and I wish I could remove that test item from the pull request.. I am not sure how though..

**Comment by esod** [comment]
I'm busy all day today, Craig. I'll have some time to look at your pull request this evening.

**Comment by ForestMars** [comment]
@Offlein If we were using the Shared Repository Model rather than individual forks (aka "Fork and Pull Model") this would be a cinch. 

So for this workflow I would have to fork your fork, reverse the commit, push back to my fork and issue a pull request against your fork, which you can merge in, and then update this pull request to get it in. Yeesh. If we were set up (correctly) with an organization this would be much easier. 

Also, we should make sure that all work is being done in topic branches, not master. (Github: "it's recommended that a topic branch be used so that follow-up commits can be pushed to update the pull request.") It's just asking for trouble to have everyone working on their own version of master and pull requesting against the "master master."

**Comment by ForestMars** [comment]
Actually, I don't think Github lets you fork a fork of a fork, so the fork I made is a fork of the original repo not the fork. So our development model (using Pull and Fork) is somewhat broken in that it doesn't seem like you can pull request from one fork to another? 

If this all seems confusing, the Shared Repository Model is much simpler, and is designed for the kind of shared collaborative work we are going. The Fork and Pull model is rather intended when you come across someone else's project you wish to contribute to, and not for teams who are already working together. 

So, we can use the fix-test branch in which I reversed the test commit. However before we merge it into Master I'd like to add feature_override module and move the cod_session module changes there. 

Really it would have been easier to just delete the test file and squash the commits.

**Comment by rabellamy** [comment]
Thy only issue was not being on a topic branch. One can make pull requests between forks. ex. https://github.com/rabellamy/nyccamp2014/pull/1

**Pull request closed without merging**
