### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by willykaram**
Adding Responsive Grid and a few Relations modules for purposes of session scheduling. Adding memory limit module back to code base, this can be used to solve PHP memory limit errors that we're encountering.

### CODE REVIEW

**Comment by willykaram** [comment]
Closing my own pull request as this is simply add some needed modules and nobody else is online ad the moment and this is time sensitive.

**Comment by esod** [comment]
What happened?
what-happened

**Comment by esod** [comment]
I moved live's database to test. Same problem

**Comment by esod** [comment]
I disabled the new modules on test. The problem persists.

**Comment by esod** [comment]
From https://drupal.org/project/role_memory_limit...

Requirements
Permission to change php memory limit on your webserver.

It's unlikely we have permission to change php memory limit on our webserver.

**Comment by esod** [comment]
Has anyone looked at this issue? The site's broken. We shouldn't commit any more work until it's been resolved.

**Comment by willykaram** [comment]
Eric - This has been resolved. We were running into PHP Memory Limit errors
on the back end of the site. The Role Memory Limit module lets us increase
the memory limit per role through the UI (as opposed to having to do that
in settings.php, which add some additional complication to people's local
config/workflow. The memory limit issues started to arise as we added mor
entity references relating to the new info architecture for the scheduling
functionality in COD. You have the site admin admin role, so shouldn't be
encountering this error, can you check the status report to see what memory
limit you are seeing when logged in:
http://www.nyccamp.org/admin/reports/status.

**Comment by esod** [comment]
It's a relief that this was resolved. It must have been browser caching that still show the broken page to me just now.

**Comment by esod** [comment]
I'm concerned that Role Memory Limit module doesn't do anything. Looking at its code all the module seems to do is send admin user input into the variables table. How does that affect php memory allocation? Can system memory limits be changed in the settings.php? Also, if the module works, we can't just add more memory in the admin, like 512, when the system memory is 256. That can't work. 

But if this is an issue for users, it's good we're trying something ...

**Comment by likewhoa** [comment]
I really dislike all these new module additions :(

**Comment by willykaram** [comment]
Fernando - Which modules specifically?

**Pull request merged**
