### PR TITLE
Theming for Keynotes pages

### PR DESCRIPTION
**Pull request by willykaram**
This is some theming relating the the keynote pages:

http://wk-theming-nyccamp2014.gotpantheon.com/session/atefeh-riazi

http://wk-theming-nyccamp2014.gotpantheon.com/keynote/robin-chase

Please review and confirm if we can push to live. Not that this is a separate DS layout that is already setup/configured on live, we just need to change the settings on the keynote nodes, which I'll do as part of pushing to live.

 Ideally we could improve some aspects, but for now it's better than what we have for those pages, which wasn't any different than the other sessions, and not really appropriate for a keynote.

### CODE REVIEW

**Comment by ForestMars** [comment]
This _looks_ good, but it has a merge conflict. 

What's that about? I'm seeing all CSS files, why do we have a merge conflict here?

**Comment by willykaram** [comment]
Sorry about that forgot the branch was behind, which lead to the conflicts. Should be fine now.

**Comment by esod** [comment]
How about adding the Add to my sessions flag to this layout? 

Looking at it on 

http://wk-theming-nyccamp2014.gotpantheon.com/session/atefeh-riazi

I see the flag has just shown in up green. and it seems to be printing on top of something. What's with the green? What's it printing on top of?

Glad you are adding the flag, though. It should definitely be there.

**Comment by esod** [comment]
Use my styling, bold and blue, which was merged in some time ago, please

**Comment by esod** [comment]
Typography is a subtle art. The flag pops nicely on this page.

http://www.nyccamp.org/session/apps-and-start-summit-wrap

**Comment by esod** [comment]
Let's not start rethinking the Drupal UX, whose established notion is words are buttons. Think about it. People unfamiliar with Drupal don't know that words are buttons until they're told. I'm sure everyone reading this post has had the experience of telling a client to click a button and the client saying "What button?", and you saying the blue word. 

But that's a much larger discussion than making the flags not clash with the rest of the page.

**Pull request merged**
