### PR TITLE
Add a rule to redirect non-admin users

### PR DESCRIPTION
**Pull request by esod**
This is another solution to the issue of the node/add page being visible to non-admin users ( https://github.com/NYC-Camp/website/pull/60 ). I think this solution works well and it is an easy solution to work with and add additional paths to, should the need arise. 

Once the dust settles on what we're going to do with COD, we can perhaps fold this module's functionality into one of the larger COD modules, like COD Sessions, for example

Please review @jonpugh and @likewhoa

### CODE REVIEW

**Comment by hubdrop-user** [comment]
I appreciate the research, eric, but I really think this is overkill. This
problem has taken up too much of our time already.

In general I prefer code to extra modules + rules. Hooks are so easy to
implement, adding modules and rules for something so simple is adding
unnecessary complexity and much more code to maintain.

Let's just deploy something and call it a day.

**Comment by jonpugh** [comment]
Oops, that was me. I guess I need to watch what email I reply to!

**Comment by likewhoa** [comment]
I agree with @jonpugh's statement, rules is overkill for this _workaround_ to our permissions issue. We either use the code I made and or @jonpugh's hook_menu_alter code which I prefer to my own method since it's more tied into drupal and use of user_access() is the prefer way of checking user permissions in code.

**Comment by ForestMars** [comment]
Closing this PR; are there PR's for @jonpugh's hook_menu_alter & @likewhoa's user_access check? Obvsly, we need to next decide which to use.

**Pull request closed without merging**
