### PR TITLE
removes $cookie_domain. Adds $_SERVER settings to settings.php

### PR DESCRIPTION
**Pull request by esod**

### CODE REVIEW

**Comment by ForestMars** [comment]
Do we really want to redirect nyccamp.org to www.nyccamp.org? I had asked this question last night in IRC bc my understanding is that was the older way of doing things, however I am under the impression there is no longer any problem doing it the other way round, ie, redirecting from www to the apex domain. 

I think that is much cleaner and would prefer it myself. Redirecting to www just feels old school, and reminds me of my grandma who constantly adds "www" to any website she is talking about. eg. 

"Did you try searching that on double-u-double-u-double-u.google.com? That's what I use" 

"I just posted pictures of my grandkids on double-u-double-u-double-u.facebook.com, Ethel, did you see them yet...?"

etc.

**Comment by esod** [comment]
Do we want to resolve this at the DNS level? 
domains-on-pantheon

**Comment by ForestMars** [comment]
That seems like cleaner approach, right? What's the proposed solution?

**Comment by esod** [comment]
Let's have a look at the DNS records. Where are they?

**Comment by esod** [comment]
BTW, I've been using:

git update-index --assume-unchanged sites/default/settings.php

whose opposite command is

git update-index --no-assume-unchanged sites/default/settings.php

Since we are supporting different settings.php depending on whether one is using kalabox or not.

**Comment by rabellamy** [comment]
http://source.kohlerville.com/2009/02/untrack-files-in-git/

**Comment by ForestMars** [comment]
@esod - obvsly not gonna post here. pm on irc pls.

**Pull request merged**
