### PR TITLE
menu_tokens for Personal Schedule. CSS tweaks for /session-schedule

### PR DESCRIPTION
**Pull request by esod**
I need a module. I tried and I tried to get this done in code, but the module does the job. <strong><em>The job</em></strong> is making the My Profile -> My Registrations link and the My Profile -> My Sessions link in the Main menu dynamic. The result of making the links dynamic is to provide immediate access for our users to their Sessions and their Registrations. Sweet.

Included in this pull request are several css tweaks for program/session-schedule.

You can see it in action at:

http://qr-code3-nyccamp2014.gotpantheon.com/

on any page that has the main menu.

### CODE REVIEW

**Comment by likewhoa** [comment]
:+1:

**Comment by esod** [comment]
Great. So merge it in. @rabellamy doesn't have to be the one. Thanks!

**Comment by willykaram** [comment]
Agreed, I've used menu tokens lots and it pretty useful.

**Comment by esod** [comment]
One thing of note. We cannot cache the Personal Schedule view. If we do, when a user clicks Add to my Sessions/Remove from my sessions, one minute must pass until user/%/my-sessions, user/%/my-registration updates. That won't do.

**Pull request merged**
