### PR TITLE
removes aside from team page

### PR DESCRIPTION
**Pull request by rabellamy**

### CODE REVIEW

**Comment by mirie** [comment]
Hey @rabellamy, we might have a small problem here -- I'm not into the aside (goodbye!) but we have promised to have the sponsor spotlight on all pages on the site -- can you make sure that team page has this somewhere? Thanks!

**Comment by ForestMars** [comment]
Good catch Mai!

**Comment by rabellamy** [comment]
@mirie it will go in the footer above lead sponsors

**Comment by mirie** [comment]
Good stuff.

**Pull request merged**
