### PR TITLE
Adding Login Destination Module

### PR DESCRIPTION
**Pull request by willykaram**
Simply commit adding Login Destination module, and adding Eric/Ferdados recent revs

### CODE REVIEW

**Comment by ForestMars** [comment]
Can we get an explanation of what this for, rather than just a randomly added module? 

As I thought was clearly discussed in other threads, paths and redirects were already a bit messed up, and this is an area that's easy to give yourself enough rope in. 

Just a simple explanation of the reason for adding this module will suffice.

**Comment by willykaram** [comment]
@ForestMars this modules was requested 3 times in other issues over the last week. Two to 3 key uses are (i) directing attendees to the correct page upon login and (ii) directing volunteers to the correct login page. Apart from the prior requests, as per the prior agreement a few of us were permitted to act as 'gatekeepers' and make basic commits to integration (including me), particularly relating to adding or (safely) updating a module. This was agreed upon/documented in the workflow call on Sun Mar 2.

**Comment by ForestMars** [comment]
Great, as I said this just needs to be documented. 

It is worth noting that a 'call' is not documentation, quite the opposite.

**Comment by willykaram** [comment]
@ForestMars it was discussed on the call and included in the documentation that day. It appears not to have been moved from the GoogleDoc 
- https://docs.google.com/a/willykaram.com/document/d/16sJ1lHYYu3u37jyXgQcDN66VHCAoF4mStiWW5WMjUbw/edit

to the Wiki
- https://github.com/NYC-Camp/website/wiki/Pantheon-Github-Workflow)

We can discuss on the call tomorrow, and amend the Wiki/Workflow documentation if needed.

You'll recall that Eric was originally serving as the sole gatekeeper for some of this routine/maintenance work.

**Pull request merged**
